apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-department
  labels:
    app: master-department
spec:
  replicas: 1
  template:
    metadata:
      name: master-department
      labels:
        app: master-department
    spec:
      containers:
        - name: master-department
          image: batsaikhan84/master-department:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: master-department