server:
  port: 8000
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: department-master
          uri: lb://DEPARTMENT-MASTER
          predicates:
            - Path=/ims.p12/api/v1/department-master/**
        - id: departments
          uri: lb://DEPARTMENTS
          predicates:
            - Path=/ims.p12/api/v1/departments/**
        - id: email
          uri: lb://EMAIL
          predicates:
            - Path=/ims.p12/api/v1/email/**
        - id: master
          uri: lb://MASTER
          predicates:
            - Path=/ims.p12/api/v1/master/**
        - id: master-department
          uri: lb://MASTER-DEPARTMENT
          predicates:
            - Path=/ims.p12/api/v1/master-department/**
        - id: request-list
          uri: lb://REQUEST-LIST
          predicates:
            - Path=/ims.p12/api/v1/request/list/**
        - id: request-make
          uri: lb://REQUEST-MAKE
          predicates:
            - Path=/ims.p12/api/v1/request/make/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: true