server:
  port: 8443
  ssl:
    key-store: classpath:ims_cert_with_key.jks
    key-store-password: changeit
    key-store-type: JKS
    key-alias: ims_key_cert
    key-password: changeit
    enabled: true
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: department-master
          uri: lb://DEPARTMENT-MASTER
          predicates:
            - Path=/ims/api/v1/department-master/**
        - id: users
          uri: lb://PROFILE-DETAILS
          predicates:
            - Path=/ims/api/v1/profile-details/**
        - id: download
          uri: lb://DOWNLOAD
          predicates:
            - Path=/ims/api/v1/download/**
        - id: store-room-master
          uri: lb://STORE-ROOM-MASTER
          predicates:
            - Path=/ims/api/v1/store-room-master/**
        - id: store-room
          uri: lb://STORE-ROOM
          predicates:
              - Path=/ims/api/v1/store-room/**
        - id: departments
          uri: lb://DEPARTMENTS
          predicates:
            - Path=/ims/api/v1/departments/**
        - id: email
          uri: lb://EMAIL
          predicates:
            - Path=/ims/api/v1/email/**
        - id: master
          uri: lb://MASTER
          predicates:
            - Path=/ims/api/v1/master/**
        - id: master-department
          uri: lb://MASTER-DEPARTMENT
          predicates:
            - Path=/ims/api/v1/master-department/**
        - id: request-master
          uri: lb://REQUEST-MASTER
          predicates:
            - Path=/ims/api/v1/request-master/**
        - id: request
          uri: lb://REQUEST
          predicates:
            - Path=/ims/api/v1/request/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true