server:
  port: 8060
  servlet:
    context-path: /ims/api/v1/request
spring:
  application:
    name: request
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_SERVER_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
  profiles:
    active: local