server:
  port: 8040
  servlet:
    context-path: /ims/api/v1/master
spring:
  application:
    name: master
  datasource:
    url: jdbc:mysql://67.184.165.195:3306/inventory
    username: root
    password: Y91permhjwb%
  jpa:
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false