server:
  port: 9100
  servlet:
    context-path: /ims/api/v1/department
spring:
  application:
    name: department
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_SERVER_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  profiles:
    active: local